### ISSUE TITLE
The markdown includes

### ISSUE THREAD

**Issue by bep** [XhmikosR/bootstrap#1]
Re. 

```
 {{< partial "callout-warning-color-assistive-technologies.md" >}} 
```

The partial above uses the `partial` func to load, parse and execute templates. This has its limitations and is possibly ineffective.

I would recommend that you store your callouts (and other content files you want to include) in a so-called headless bundle -- and load them via `.GetPage`. This way you can use markdown + shortcodes etc.

**Comment by XhmikosR** [comment]
Not sure how to do that, though :)

**Comment by XhmikosR** [comment]
I moved this issue in the PR TODO and I will create news issues upstream if we don't have a fix befoe the PR merge.

Thanks for the suggestion!
