### ISSUE TITLE
Markdown isn't rendered as HTML in a specific case

### ISSUE THREAD

**Issue by XhmikosR** [XhmikosR/bootstrap#3]
Figure out/report why https://github.com/XhmikosR/bootstrap/blob/v4-dev-xmr-hugo-2/site/content/docs/4.2/components/dropdowns.md#directions isn't rendered.

Live preview: https://deploy-preview-28014--twbs-bootstrap4.netlify.com/docs/4.2/components/dropdowns/#sizing

Just scroll down a bit to see the issue @bep

**Comment by XhmikosR** [comment]
OK, it seems it's because of the HTML comment above https://github.com/XhmikosR/bootstrap/commit/107cce349ea3caffb87106ba59115f8694a4a806

Should this happen though?

**Comment by bep** [comment]
>Should this happen though?

If you have very detailed questions/issues about the Markdown rendered, you need to take it here:

https://github.com/russross/blackfriday/issues

I know a lot, but you cannot expect me to know every little defail. I looks to me, however, that you found a good workaround.

**Comment by XhmikosR** [comment]
Not sure it's a BF issue, because the comment that caused this, matched a shortcode `example`.

**Comment by XhmikosR** [comment]
@bep should I make an issue in the Hugo repo and if you are sure it's a BF issue I can make an issue there.

I reduced the issue to this:

```html
---
layout: docs
title: Dropdowns
description: Toggle contextual overlays for displaying lists of links and more with the Bootstrap dropdown plugin.
group: components
toc: true
---

## Sizing

Button dropdowns work with buttons of all sizes, including default and split dropdown buttons.

## foo

<div class="bd-example"></div><!-- /whatever comment here -->

## this isn't rendered as HTML

{{< highlight html >}}
<!-- Large button groups (default and split) -->
<div class="btn-group">
  <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Large button
  </button>
  ...
</div>
{{< /highlight >}}

## this isn't rendered as HTML either

### neither is this

Trigger dropdown menus above elements by adding `.dropup` to the parent element.

<div class="bd-example">
  <div class="btn-group dropup">
    <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Dropup
    </button>
  </div>
</div>

```

**Comment by XhmikosR** [comment]
OK I reported all this to Blackfriday.
