### ISSUE TITLE
`/docs/index.html` isn't a redirect

### ISSUE THREAD

**Issue by XhmikosR** [XhmikosR/bootstrap#4]
@bep for some reason that URL should be a redirect as specified in https://github.com/XhmikosR/bootstrap/blob/v4-dev-xmr-hugo-2/site/content/docs/4.2/getting-started/introduction.md

Preview: https://deploy-preview-28014--twbs-bootstrap4.netlify.com/docs/

Yet it's a normal page. Is it because the layouts hierarchy is wrong?

**Comment by bep** [comment]
You have duplicate output of the same path. You need to disable `section` creation -- look for `disableKinds` in the Hugo docs.

**Comment by XhmikosR** [comment]
Ah, thanks! Didn't even think about this.
