### ISSUE TITLE
Fix individual examples

### ISSUE THREAD

**Issue by XhmikosR** [XhmikosR/bootstrap#5]
@bep when you have some time, this is the remaining templates issues. Must be the lookup order I'm missing something.

Then we still have a few cases of inline HTML in content files that I couldn't solve.

**Comment by XhmikosR** [comment]
I fixed this by adding an _index.md in examples, but I had to enable `sections` in the config. Now `/docs/index.html` doesn't contain the redirect, see #4

**Comment by XhmikosR** [comment]
I think the templates order is not right, or it's a bug.

`/docs/index.html` should be a redirect but now it's again a page because I had to reenable `sections` kind for the individual examples to be built.

**Comment by bep** [comment]
>I think the templates order is not right, or it's a bug.

No, it works as designed. You cannot have 2 files published to the same location, so `docs/index.html` needs to be either a redirect or not. Not both.

**Comment by bep** [comment]
You can start by explaining why it has to be a redirect?

**Comment by bep** [comment]
OK, what I suggest is this (there may be other approaches, but this is my first thought):

* Drop the alias thing for this particular use
* Add `docs/_index.html` with a meta refresh that redirects to the latest version (I assume you have a site param you can pick up)

An added note:

I don't know where you host your site, but I would recommend you look into Netlify. They have free premium plans for open source projects. And they have a redirects feature that does proper 301 server  side redirects. You can have a look at the gohugo.io source code, but we basically:

1. Turn of alias redirect generation
2. Create a Netlify redirect file based on the alias definitions

**Comment by XhmikosR** [comment]
Yeah, I'm aware of Netlify but for reasons out of my jurisdiction I don't think we can move to Netlify. We already use it for PR previews BTW.

Thanks for the suggestion, I'll see what I can do tomorrow. I still need to fix the examples shortcode.

**Comment by bep** [comment]
One other option is to put `docs/_index.md` with either 

`url : /somedummy` ... will create an extra page.

or

`layout:  doesnotexist` ... will create a build warning.

In frontmatter

Both the above hacks would make the alias file survive ... But I would suggest you take my suggestion above.

**Comment by XhmikosR** [comment]
This is done, although I'm still not sure about our content structure. I mean, if we could simplify it in any way, I'd really like that. So that `examples/` work and we don't need to work around the redirects issue.

Or if we could skip the `docs/4.2/` folders and specify the output somewhere else or something.

Not a deal breaker, just trying to keep things as simple as possible.
