### ISSUE TITLE
Blocks in templates

### ISSUE THREAD

**Issue by bep** [XhmikosR/bootstrap#7]
Ref. `{{ block "header" . }}` in your `single.html` template.

Blocks only make sense inside base template(s) (i.e. `baseof.html`), which I cannot see.  I would highly recommend that you restructure your templates to use them. It removes some repetition. Also, since Bootstrap is such a popular project, I guess many will follow the examples you provide, and then it would be good if it spread the right ways to do stuff in Hugo.

**Comment by XhmikosR** [comment]
Yeah, that's what I'm asking you for or from someone who's more familiar than I with the templates part :)

Currently I want to finish everything so that we can merge and then submit PRs to the main project. I won't wait for v5 to merge the Hugo switch because I really want to make it ASAP.

**Comment by XhmikosR** [comment]
I moved this issue in the PR TODO and I will create news issues upstream if we don't have a fix befoe the PR merge.

Thanks for the suggestion!
